DROP TABLE IF EXISTS sales_history;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;

CREATE TABLE partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_type VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    director_name VARCHAR(255) NOT NULL,
    inn VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    phone VARCHAR(32),
    rating NUMERIC(2, 1) CHECK (rating BETWEEN 0 AND 5)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(64) NOT NULL UNIQUE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0)
);

CREATE TABLE sales_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id BIGINT NOT NULL REFERENCES partners(id) ON DELETE RESTRICT,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    sale_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE INDEX sales_history_partner_id_idx ON sales_history (partner_id);

INSERT INTO partners (id, partner_type, name, director_name, inn, email, phone, rating)
VALUES
    (1, 'ООО', 'Логистик-Экспресс', 'Иванов Илья Сергеевич', '7701234567', 'info@logex.ru', '+79991112233', 4.8),
    (2, 'ИП', 'Петров А.В.', 'Петров Алексей Викторович', '5001098765', 'petrov_delivery@mail.ru', NULL, 4.2),
    (3, 'ТК', 'Быстрый Путь', 'Смирнова Елена Олеговна', '7812345678', 'speedway@yandex.ru', '+78125554433', NULL),
    (4, 'ООО', 'Северный Склад', 'Кузнецов Максим Андреевич', '6601001122', 'office@northstore.ru', '+73432990011', 3.9);

INSERT INTO products (id, name, sku, price)
VALUES
    (1, 'Стиральный порошок "Альфа"', 'PRODUCT-001', 500.00),
    (2, 'Мыло жидкое "Стандарт"', 'PRODUCT-002', 90.00),
    (3, 'Кондиционер для белья', 'PRODUCT-003', 350.00);

INSERT INTO sales_history (id, partner_id, product_id, quantity, sale_date)
VALUES
    (1, 1, 1, 50, '2026-03-01'),
    (2, 2, 2, 200, '2026-03-15'),
    (3, 1, 3, 30, '2026-03-20'),
    (4, 3, 2, 150, '2026-03-25'),
    (5, 1, 1, 9920, '2026-04-01'),
    (6, 2, 2, 49800, '2026-04-01'),
    (7, 3, 3, 299850, '2026-04-01');

SELECT setval(pg_get_serial_sequence('partners', 'id'), (SELECT MAX(id) FROM partners));
SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT MAX(id) FROM products));
SELECT setval(pg_get_serial_sequence('sales_history', 'id'), (SELECT MAX(id) FROM sales_history));
