DROP TABLE IF EXISTS sales_history;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;

CREATE TABLE partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_type VARCHAR(100) NOT NULL CHECK (partner_type IN ('ООО', 'ЗАО', 'ИП', 'ТК')),
    name VARCHAR(255) NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 0),
    address VARCHAR(500) NOT NULL,
    director_name VARCHAR(255) NOT NULL,
    phone VARCHAR(32),
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(64) NOT NULL UNIQUE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0)
);

CREATE TABLE sales_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id BIGINT NOT NULL REFERENCES partners(id) ON DELETE RESTRICT,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    sale_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE INDEX sales_history_partner_id_idx ON sales_history (partner_id);

INSERT INTO partners (id, partner_type, name, rating, address, director_name, phone, email)
VALUES
    (1, 'ООО', 'Логистик-Экспресс', 5, 'г. Москва, ул. Складская, д. 12', 'Иванов Илья Сергеевич', '+7 (999) 111-22-33', 'info@logex.ru'),
    (2, 'ИП', 'Петров А.В.', 4, 'г. Химки, Транспортный проезд, д. 7', 'Петров Алексей Викторович', NULL, 'petrov.delivery@mail.ru'),
    (3, 'ТК', 'Быстрый Путь', 5, 'г. Санкт-Петербург, Лиговский проспект, д. 81', 'Смирнова Елена Олеговна', '+7 (812) 555-44-33', 'speedway@yandex.ru'),
    (4, 'ЗАО', 'Северный Склад', 3, 'г. Екатеринбург, Северное шоссе, д. 4', 'Кузнецов Максим Андреевич', '+7 (343) 299-00-11', 'office@northstore.ru');

INSERT INTO products (id, name, sku, price)
VALUES
    (1, 'Стиральный порошок "Альфа"', 'PRODUCT-001', 500.00),
    (2, 'Мыло жидкое "Стандарт"', 'PRODUCT-002', 90.00),
    (3, 'Кондиционер для белья', 'PRODUCT-003', 350.00);

INSERT INTO sales_history (id, partner_id, product_id, quantity, sale_date)
VALUES
    (1, 1, 1, 50, '2026-03-01'),
    (2, 2, 2, 200, '2026-03-15'),
    (3, 1, 3, 30, '2026-03-20'),
    (4, 3, 2, 150, '2026-03-25'),
    (5, 1, 1, 9920, '2026-04-01'),
    (6, 2, 2, 49800, '2026-04-01'),
    (7, 3, 3, 299850, '2026-04-01');

SELECT setval(pg_get_serial_sequence('partners', 'id'), (SELECT MAX(id) FROM partners));
SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT MAX(id) FROM products));
SELECT setval(pg_get_serial_sequence('sales_history', 'id'), (SELECT MAX(id) FROM sales_history));
