DROP TABLE IF EXISTS sales_history;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS partners;

CREATE TABLE partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_type VARCHAR(10) NOT NULL CHECK (partner_type IN ('ООО', 'ЗАО', 'ИП', 'ТК')),
    name VARCHAR(255) NOT NULL,
    address VARCHAR(500) NOT NULL,
    director_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(32),
    rating INTEGER NOT NULL CHECK (rating >= 0)
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(64) NOT NULL UNIQUE,
    price NUMERIC(10, 2) NOT NULL CHECK (price > 0)
);

CREATE TABLE sales_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id BIGINT NOT NULL REFERENCES partners(id) ON DELETE RESTRICT,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    sale_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE INDEX sales_history_partner_id_idx ON sales_history (partner_id);

INSERT INTO partners (id, partner_type, name, address, director_name, email, phone, rating)
VALUES
    (1, 'ООО', 'Логистик-Экспресс', 'г. Москва, ул. Складская, д. 10', 'Иванов Илья Сергеевич', 'info@logex.ru', '+79991112233', 8),
    (2, 'ИП', 'Петров А.В.', 'Московская обл., г. Химки, пр-т Мира, д. 4', 'Петров Алексей Викторович', 'petrov_delivery@mail.ru', NULL, 7),
    (3, 'ТК', 'Быстрый Путь', 'г. Санкт-Петербург, Лиговский пр-т, д. 80', 'Смирнова Елена Олеговна', 'speedway@yandex.ru', '+78125554433', 9),
    (4, 'ЗАО', 'Северный Склад', 'г. Екатеринбург, ул. Промышленная, д. 15', 'Кузнецов Максим Андреевич', 'office@northstore.ru', '+73432990011', 6);

INSERT INTO products (id, name, sku, price)
VALUES
    (1, 'Стиральный порошок "Альфа"', 'PRODUCT-001', 500.00),
    (2, 'Мыло жидкое "Стандарт"', 'PRODUCT-002', 90.00),
    (3, 'Кондиционер для белья', 'PRODUCT-003', 350.00);

INSERT INTO sales_history (id, partner_id, product_id, quantity, sale_date)
VALUES
    (1, 1, 1, 50, '2026-03-01'),
    (2, 2, 2, 200, '2026-03-15'),
    (3, 1, 3, 30, '2026-03-20'),
    (4, 3, 2, 150, '2026-03-25'),
    (5, 1, 1, 9920, '2026-04-01'),
    (6, 2, 2, 49800, '2026-04-01'),
    (7, 3, 3, 299850, '2026-04-01');

SELECT setval(pg_get_serial_sequence('partners', 'id'), (SELECT MAX(id) FROM partners));
SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT MAX(id) FROM products));
SELECT setval(pg_get_serial_sequence('sales_history', 'id'), (SELECT MAX(id) FROM sales_history));
